on:
  #schedule:
  #  - cron: '0 3 */4 * *'
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download and uplift files
        run: |
          pip install ogc-na
          python -m ogc.na.download --spec .ogc/file-downloads.yaml
          for FILE in ontology/*.csv ; do
            python -m ogc.na.ingest_json --skip-on-missing-context --json-ld --context .ogc/csv2json.yml \
            --json-ld-file "${FILE}.json" "${FILE}" 
          done
          
          for FILE in ontology/*.csv.json ; do
            python -m ogc.na.ingest_json --skip-on-missing-context --ttl --ttl-file "${FILE%.csv.json}.ttl" "${FILE}"
          done
      - name: Commit new versions of files
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: "Downloaded new versions of documents"
          default_author: github_actions

